### ISSUE TITLE
[BUG] W/O ColumnSelector gives different result. Is this a expected behavior?

### ISSUE THREAD

**Issue by YKX-A** [NVIDIA-Merlin/NVTabular#1316]
**Describe the bug**
With and without `ColumnSelector` produce different results. If I'm not misusing the library, it might be a bug.

**Steps/Code to reproduce bug**

The difference between the below codes is in columns `categories` and `productID`. It seems that the differences are caused by the `Categorify` operator, which treats columns with and without ColumnSelector differently.

1. with `ColumnSelector`
```python
import cudf
import nvtabular as nvt
from nvtabular import ColumnSelector

# Create toy dataset
df = cudf.DataFrame({
    'userID': [11, 22, 33, None],
    'productID': [30003, 30005, 40005, 50005],
    'categories': [130003, 130005, 140005, 150005],
    'label': [0,0,1, None]
})
dataset = nvt.Dataset(df)
fill_miss =  ['userID'] >> nvt.ops.FillMedian()  >> nvt.ops.Rename(postfix = '_filled')
cate = fill_miss + ColumnSelector(['categories', 'productID']) >> nvt.ops.Categorify()  # with ColumnSelector

# Initialize the workflow and execute it
proc = nvt.Workflow(cate)
proc.fit(dataset)
ddf = proc.transform(dataset).to_ddf()
ddf = ddf.compute()
ddf
```

2. without `ColumnSelector`
```python
# Create toy dataset
df = cudf.DataFrame({
    'userID': [11, 22, 33, None],
    'productID': [30003, 30005, 40005, 50005],
    'categories': [130003, 130005, 140005, 150005],
    'label': [0,0,1, None]
})
dataset = nvt.Dataset(df)
fill_miss =  ['userID'] >> nvt.ops.FillMedian()  >> nvt.ops.Rename(postfix = '_filled')
cate = fill_miss + ['categories', 'productID'] >> nvt.ops.Categorify() # without ColumnSelector

# Initialize the workflow and execute it
proc = nvt.Workflow(cate)
proc.fit(dataset)
ddf = proc.transform(dataset).to_ddf()
ddf = ddf.compute()
ddf
```

Furthermore, this line seems also important to cause the differences:
```python
fill_miss =  ['userID'] >> nvt.ops.FillMedian()  >> nvt.ops.Rename(postfix = '_filled')
```
Because if there is no `fill_miss`, with and without `ColumnSelector` will give the same result.
```python
cate = ColumnSelector(['categories', 'productID']) >> nvt.ops.Categorify()
proc = nvt.Workflow(cate)
proc.fit(dataset)
ddf = proc.transform(dataset).to_ddf()
ddf = ddf.compute()
ddf
```

```python
cate = ['categories', 'productID'] >> nvt.ops.Categorify()
proc = nvt.Workflow(cate)
proc.fit(dataset)
ddf = proc.transform(dataset).to_ddf()
ddf = ddf.compute()
ddf

```

**Expected behavior**
Both with and without `ColumnSelector` should give the same result. (?)

**Environment details (please complete the following information):**
 - Method of NVTabular install: [conda, Docker, or from source]
   - from source: `nvt.__version__` is `0.8.0+1.ga228f12`
 

**Additional context**
No Additional context

**Comment by bschifferer** [comment]
I verified the bug. I think that `2. without ColumnSelector` encodes `categories` and `productID` in the `joint` mode. `If "joint", the columns within any multi-column group will be jointly encoded.` . The workflow interprets wrongly `['categories', 'productID']` as a multi-column.

Output
1. with ColumnSelector
![image](https://user-images.githubusercontent.com/19567274/145988537-4fbdcfb1-411c-4dcd-9346-3f364657e52e.png)

2. without ColumnSelector
![image](https://user-images.githubusercontent.com/19567274/145988573-89371d99-7889-474a-8979-ee637f3df398.png)

3. If I use two `+` operators, it is correct.

```
# Create toy dataset
df = cudf.DataFrame({
    'userID': [11, 22, 33, None],
    'productID': [30003, 30005, 40005, 50005],
    'categories': [130003, 130005, 140005, 150005],
    'label': [0,0,1, None]
})
dataset = nvt.Dataset(df)
fill_miss =  ['userID'] >> nvt.ops.FillMedian()  >> nvt.ops.Rename(postfix = '_filled')
cate = fill_miss + ['categories'] + ['productID'] >> nvt.ops.Categorify() # without ColumnSelector

# Initialize the workflow and execute it
proc = nvt.Workflow(cate)
proc.fit(dataset)
ddf = proc.transform(dataset).to_ddf()
ddf = ddf.compute()
ddf
```

![image](https://user-images.githubusercontent.com/19567274/145988639-cabef2e8-aee9-48c5-89e0-c792ec49e409.png)

**Comment by karlhigley** [comment]
We think this is happening because `+` treats lists as groups of columns, and `Categorify`'s behavior depends on how columns are grouped together.

The syntax `fill_miss + ['categories', 'productID']` is a shortcut for a slightly different selector: `ColumnSelector(subgroups=[ColumnSelector(['categories', 'productID'])])` instead of `ColumnSelector(['categories', 'productID'])`.

The default for `Categorify` is to encode grouped columns jointly, meaning that it builds one look-up table that maps the values from all grouped columns to one shared set of categorical ids. When you use two `+`s, then the `categories` and `productID` columns aren't grouped together, so the output of `Categorify` is based on separate look-up tables for each column.

However, `fill_miss + ['categories'] + ['productID']` still creates a selector with subgroups: `ColumnSelector(subgroups=[ColumnSelector(['categories']),ColumnSelector(['productID'])])`. In this case, `Categorify` is still trying to build a joint look-up table across the groups of columns, but each group only has one column, so it ends up being equivalent to omitting the lists around the column names: `fill_miss + 'categories' + 'productId'`, which results in `ColumnSelector(['categories', 'productID'])` getting added to the output of `Rename`.

It's not really clear to us if this is a bug, a rough edge in the API, or a necessary evil to provide the grouping that `Categorify` relies on. 😅

**Comment by YKX-A** [comment]
Thanks for clarifying things @karlhigley, @bschifferer.
So we should pay attention to the difference between the `ColumnSelector([c1,c2])` and simple list `[c1, c2]` expression. The latter one will automatically create a subgroup.
