### ISSUE TITLE
NVTabular Movielens Tutorial error in joinExternal

### ISSUE THREAD

**Issue by Pelps12** [NVIDIA-Merlin/NVTabular#1584]
I was following the ETL tutorial for NVTabular and I ran into an issue when running 
```
joined = ["userId", "movieId"] >> nvt.ops.JoinExternal(df_ext=movies, on=["movieId"])
```
I got an attribute errror : 
```
AttributeError: 'NoneType' object has no attribute 'DataFrame'
```
Any help would be appreciated

**Comment by radekosmulski** [comment]
Hey @Pelps12!

If you are referring to `getting-started-movielens/02-ETL-with-NVTabular.ipynb`, I was just able to run it without issues. I am using `nvcr.io/nvidia/merlin/merlin-tensorflow-training:22.05` container I believe, but this should probably run regardless, I don't think it is your environment that is the culprit here.

I am wondering, did you maybe make any changes to the notebook? Would you be able to clone a fresh version of the repository or checkout a fresh version of the notebook?

Also, if you could provide a longer stack trace, that would be greatly appreciated! Thanks!
