### ISSUE TITLE
nvtabular import error :Kaggle notebook

### ISSUE THREAD

**Issue by DilipKumar3** [NVIDIA-Merlin/NVTabular#1731]
Error on importing nvtabular in kaggle notebook 
![image](https://user-images.githubusercontent.com/48671630/207284308-efd77af4-04f2-4831-b490-2035245deb6f.png)Kindly let us know on how to resolve this

**Comment by bschifferer** [comment]
@DilipKumar3 can you provide the notebook you tried on the Kaggle environment? How did you install nvtabular?

**Comment by karlhigley** [comment]
From the error message, it sounds like there's a newer version of NVTabular running against an older version of `merlin-core`. What versions of those libraries are installed?

**Comment by oliverholworthy** [comment]
This is likely to be because the Kaggle environment is running Python 3.7 and we support a min version of Python 3.8. The bug on our side is that we didn't update the `python_requires` attribute in our published package for NVTabular, to reflect the python version requirement.

Installing an older version of NVTabular may work (`pip install nvtabular==1.4.0`)

**Comment by DilipKumar3** [comment]
> pip install nvtabular==1.4.0

@bschifferer im using _**pip install nvtabula**_r for installing nvtabular.

**Comment by DilipKumar3** [comment]
like mentioned i tried by installed specific version and it worked .
thanks for the help.
